-- Lier malus aux effets : si allocation < min_pct, appliquer le malus (par effet) au lieu du bonus.
-- Chaque ministère : bonus par effet si pct >= min_pct, sinon malus par effet (maluses.{population,gdp,militarism,industry,science,stability}).

CREATE OR REPLACE FUNCTION public.run_daily_country_update()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_at timestamptz;
  pop_base numeric;
  gdp_base numeric;
  gdp_per_mil numeric;
  gdp_per_ind numeric;
  gdp_per_sci numeric;
  gdp_per_stab numeric;
  pop_per_mil numeric;
  pop_per_ind numeric;
  pop_per_sci numeric;
  pop_per_stab numeric;
BEGIN
  v_run_at := now();

  INSERT INTO public.country_history (country_id, date, population, gdp, militarism, industry, science, stability)
  SELECT c.id, current_date, c.population, c.gdp, c.militarism, c.industry, c.science, c.stability
  FROM public.countries c
  ON CONFLICT (country_id, date)
  DO UPDATE SET population = EXCLUDED.population, gdp = EXCLUDED.gdp, militarism = EXCLUDED.militarism, industry = EXCLUDED.industry, science = EXCLUDED.science, stability = EXCLUDED.stability;

  SELECT COALESCE((value #>> '{}')::numeric, 0.001) INTO pop_base FROM public.rule_parameters WHERE key = 'population_growth_base_rate' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0.0005) INTO gdp_base FROM public.rule_parameters WHERE key = 'gdp_growth_base_rate' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO gdp_per_mil FROM public.rule_parameters WHERE key = 'gdp_growth_per_militarism' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO gdp_per_ind FROM public.rule_parameters WHERE key = 'gdp_growth_per_industry' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO gdp_per_sci FROM public.rule_parameters WHERE key = 'gdp_growth_per_science' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO gdp_per_stab FROM public.rule_parameters WHERE key = 'gdp_growth_per_stability' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO pop_per_mil FROM public.rule_parameters WHERE key = 'population_growth_per_militarism' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO pop_per_ind FROM public.rule_parameters WHERE key = 'population_growth_per_industry' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO pop_per_sci FROM public.rule_parameters WHERE key = 'population_growth_per_science' LIMIT 1;
  SELECT COALESCE((value #>> '{}')::numeric, 0) INTO pop_per_stab FROM public.rule_parameters WHERE key = 'population_growth_per_stability' LIMIT 1;

  WITH
  pop_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('population_growth_base', 'population_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  gdp_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('gdp_growth_base', 'gdp_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  stat_effects AS (SELECT country_id, COALESCE(SUM(value) FILTER (WHERE effect_target = 'militarism'), 0) AS delta_mil, COALESCE(SUM(value) FILTER (WHERE effect_target = 'industry'), 0) AS delta_ind, COALESCE(SUM(value) FILTER (WHERE effect_target = 'science'), 0) AS delta_sci, COALESCE(SUM(value) FILTER (WHERE effect_target = 'stability'), 0) AS delta_stab FROM public.country_effects WHERE effect_kind = 'stat_delta' AND duration_remaining > 0 AND effect_target IN ('militarism', 'industry', 'science', 'stability') GROUP BY country_id),
  budget_bonuses AS (
    SELECT b.country_id,
      (CASE WHEN b.pct_sante >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) THEN (b.pct_sante/100.0)*COALESCE((SELECT (value->'bonuses'->>'population')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) - b.pct_sante) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'population')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), -0.05) END) AS pop_rate,
      (CASE WHEN b.pct_infrastructure >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) THEN (b.pct_infrastructure/100.0)*COALESCE((SELECT (value->'bonuses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) - b.pct_infrastructure) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_affaires_etrangeres >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE((SELECT (value->'bonuses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05) END) AS gdp_rate,
      (CASE WHEN b.pct_defense >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) THEN (b.pct_defense/100.0)*COALESCE((SELECT (value->'bonuses'->>'militarism')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) - b.pct_defense) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'militarism')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), -0.05) END) AS mil_delta,
      (CASE WHEN b.pct_infrastructure >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) THEN (b.pct_infrastructure/100.0)*COALESCE((SELECT (value->'bonuses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) - b.pct_infrastructure) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_industrie >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) THEN (b.pct_industrie/100.0)*COALESCE((SELECT (value->'bonuses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) - b.pct_industrie) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), -0.05) END) AS ind_delta,
      (CASE WHEN b.pct_education >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) THEN (b.pct_education/100.0)*COALESCE((SELECT (value->'bonuses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) - b.pct_education) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_recherche >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) THEN (b.pct_recherche/100.0)*COALESCE((SELECT (value->'bonuses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) - b.pct_recherche) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), -0.05) END) AS sci_delta,
      (CASE WHEN b.pct_education >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) THEN (b.pct_education/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) - b.pct_education) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_interieur >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) THEN (b.pct_interieur/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) - b.pct_interieur) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_affaires_etrangeres >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05) END) AS stab_delta
    FROM public.country_budget b
  ),
  country_updates AS (SELECT c.id AS country_id, COALESCE(pe.rate, 0) AS pop_effect_rate, COALESCE(ge.rate, 0) AS gdp_effect_rate, COALESCE(se.delta_mil, 0) AS delta_mil, COALESCE(se.delta_ind, 0) AS delta_ind, COALESCE(se.delta_sci, 0) AS delta_sci, COALESCE(se.delta_stab, 0) AS delta_stab, COALESCE(bb.pop_rate, 0) AS budget_pop_rate, COALESCE(bb.gdp_rate, 0) AS budget_gdp_rate, COALESCE(bb.mil_delta, 0) AS budget_mil, COALESCE(bb.ind_delta, 0) AS budget_ind, COALESCE(bb.sci_delta, 0) AS budget_sci, COALESCE(bb.stab_delta, 0) AS budget_stab FROM public.countries c LEFT JOIN pop_effects pe ON pe.country_id = c.id LEFT JOIN gdp_effects ge ON ge.country_id = c.id LEFT JOIN stat_effects se ON se.country_id = c.id LEFT JOIN budget_bonuses bb ON bb.country_id = c.id)
  INSERT INTO public.country_update_logs (country_id, run_at, inputs, population_before, gdp_before, militarism_before, industry_before, science_before, stability_before)
  SELECT c.id, v_run_at, jsonb_build_object('pop_base', pop_base, 'gdp_base', gdp_base, 'pop_from_stats', (COALESCE(c.militarism,0)*pop_per_mil+COALESCE(c.industry,0)*pop_per_ind+COALESCE(c.science,0)*pop_per_sci+COALESCE(c.stability,0)*pop_per_stab), 'gdp_from_stats', (COALESCE(c.militarism,0)*gdp_per_mil+COALESCE(c.industry,0)*gdp_per_ind+COALESCE(c.science,0)*gdp_per_sci+COALESCE(c.stability,0)*gdp_per_stab), 'pop_effect_rate', u.pop_effect_rate, 'gdp_effect_rate', u.gdp_effect_rate, 'budget_pop_rate', u.budget_pop_rate, 'budget_gdp_rate', u.budget_gdp_rate, 'pop_total_rate', (pop_base+COALESCE(c.militarism,0)*pop_per_mil+COALESCE(c.industry,0)*pop_per_ind+COALESCE(c.science,0)*pop_per_sci+COALESCE(c.stability,0)*pop_per_stab+u.pop_effect_rate+u.budget_pop_rate), 'gdp_total_rate', (gdp_base+COALESCE(c.militarism,0)*gdp_per_mil+COALESCE(c.industry,0)*gdp_per_ind+COALESCE(c.science,0)*gdp_per_sci+COALESCE(c.stability,0)*gdp_per_stab+u.gdp_effect_rate+u.budget_gdp_rate), 'delta_mil', u.delta_mil, 'delta_ind', u.delta_ind, 'delta_sci', u.delta_sci, 'delta_stab', u.delta_stab, 'budget_mil', u.budget_mil, 'budget_ind', u.budget_ind, 'budget_sci', u.budget_sci, 'budget_stab', u.budget_stab), c.population, c.gdp, c.militarism, c.industry, c.science, c.stability FROM public.countries c JOIN country_updates u ON u.country_id = c.id;

  WITH
  pop_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('population_growth_base', 'population_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  gdp_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('gdp_growth_base', 'gdp_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  stat_effects AS (SELECT country_id, COALESCE(SUM(value) FILTER (WHERE effect_target = 'militarism'), 0) AS delta_mil, COALESCE(SUM(value) FILTER (WHERE effect_target = 'industry'), 0) AS delta_ind, COALESCE(SUM(value) FILTER (WHERE effect_target = 'science'), 0) AS delta_sci, COALESCE(SUM(value) FILTER (WHERE effect_target = 'stability'), 0) AS delta_stab FROM public.country_effects WHERE effect_kind = 'stat_delta' AND duration_remaining > 0 AND effect_target IN ('militarism', 'industry', 'science', 'stability') GROUP BY country_id),
  budget_bonuses AS (
    SELECT b.country_id,
      (CASE WHEN b.pct_sante >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) THEN (b.pct_sante/100.0)*COALESCE((SELECT (value->'bonuses'->>'population')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0) - b.pct_sante) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'population')::numeric FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), -0.05) END) AS pop_rate,
      (CASE WHEN b.pct_infrastructure >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) THEN (b.pct_infrastructure/100.0)*COALESCE((SELECT (value->'bonuses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) - b.pct_infrastructure) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_affaires_etrangeres >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE((SELECT (value->'bonuses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'gdp')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05) END) AS gdp_rate,
      (CASE WHEN b.pct_defense >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) THEN (b.pct_defense/100.0)*COALESCE((SELECT (value->'bonuses'->>'militarism')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0) - b.pct_defense) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'militarism')::numeric FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), -0.05) END) AS mil_delta,
      (CASE WHEN b.pct_infrastructure >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) THEN (b.pct_infrastructure/100.0)*COALESCE((SELECT (value->'bonuses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0) - b.pct_infrastructure) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_industrie >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) THEN (b.pct_industrie/100.0)*COALESCE((SELECT (value->'bonuses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0) - b.pct_industrie) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'industry')::numeric FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), -0.05) END) AS ind_delta,
      (CASE WHEN b.pct_education >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) THEN (b.pct_education/100.0)*COALESCE((SELECT (value->'bonuses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) - b.pct_education) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_recherche >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) THEN (b.pct_recherche/100.0)*COALESCE((SELECT (value->'bonuses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0) - b.pct_recherche) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'science')::numeric FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), -0.05) END) AS sci_delta,
      (CASE WHEN b.pct_education >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) THEN (b.pct_education/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0) - b.pct_education) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_interieur >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) THEN (b.pct_interieur/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0) - b.pct_interieur) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), -0.05) END)
      + (CASE WHEN b.pct_affaires_etrangeres >= COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE((SELECT (value->'bonuses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) ELSE ( (COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE((SELECT (value->>'min_pct')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ) * COALESCE((SELECT (value->'maluses'->>'stability')::numeric FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05) END) AS stab_delta
    FROM public.country_budget b
  ),
  country_updates AS (SELECT c.id AS country_id, COALESCE(pe.rate, 0) AS pop_effect_rate, COALESCE(ge.rate, 0) AS gdp_effect_rate, COALESCE(se.delta_mil, 0) AS delta_mil, COALESCE(se.delta_ind, 0) AS delta_ind, COALESCE(se.delta_sci, 0) AS delta_sci, COALESCE(se.delta_stab, 0) AS delta_stab, COALESCE(bb.pop_rate, 0) AS budget_pop_rate, COALESCE(bb.gdp_rate, 0) AS budget_gdp_rate, COALESCE(bb.mil_delta, 0) AS budget_mil, COALESCE(bb.ind_delta, 0) AS budget_ind, COALESCE(bb.sci_delta, 0) AS budget_sci, COALESCE(bb.stab_delta, 0) AS budget_stab FROM public.countries c LEFT JOIN pop_effects pe ON pe.country_id = c.id LEFT JOIN gdp_effects ge ON ge.country_id = c.id LEFT JOIN stat_effects se ON se.country_id = c.id LEFT JOIN budget_bonuses bb ON bb.country_id = c.id)
  UPDATE public.countries c
  SET
    population = GREATEST(0, (c.population + c.population * (pop_base + COALESCE(c.militarism, 0) * pop_per_mil + COALESCE(c.industry, 0) * pop_per_ind + COALESCE(c.science, 0) * pop_per_sci + COALESCE(c.stability, 0) * pop_per_stab + u.pop_effect_rate + u.budget_pop_rate))::bigint),
    gdp = GREATEST(0, (c.gdp + c.gdp * (gdp_base + COALESCE(c.militarism, 0) * gdp_per_mil + COALESCE(c.industry, 0) * gdp_per_ind + COALESCE(c.science, 0) * gdp_per_sci + COALESCE(c.stability, 0) * gdp_per_stab + u.gdp_effect_rate + u.budget_gdp_rate))),
    militarism = LEAST(10, GREATEST(0, ROUND((COALESCE(c.militarism, 0) + u.delta_mil + u.budget_mil)::numeric, 0)))::smallint,
    industry   = LEAST(10, GREATEST(0, ROUND((COALESCE(c.industry, 0)   + u.delta_ind + u.budget_ind)::numeric, 0)))::smallint,
    science    = LEAST(10, GREATEST(0, ROUND((COALESCE(c.science, 0)    + u.delta_sci + u.budget_sci)::numeric, 0)))::smallint,
    stability  = LEAST(3, GREATEST(-3, ROUND((COALESCE(c.stability, 0) + u.delta_stab + u.budget_stab)::numeric, 0)))::smallint,
    updated_at = now()
  FROM country_updates u
  WHERE c.id = u.country_id;

  UPDATE public.country_update_logs l SET population_after = c.population, gdp_after = c.gdp, militarism_after = c.militarism, industry_after = c.industry, science_after = c.science, stability_after = c.stability FROM public.countries c WHERE l.country_id = c.id AND l.run_at = v_run_at;

  UPDATE public.country_effects SET duration_remaining = duration_remaining - 1 WHERE duration_remaining > 0;
  DELETE FROM public.country_effects WHERE duration_remaining <= 0;
END;
$$;

COMMENT ON FUNCTION public.run_daily_country_update() IS
  'Cron quotidien. Budget : si pct >= min_pct alors bonus par effet, sinon malus par effet (maluses.{effet}).';