-- Accepter virgule ou point dans les valeurs numériques des rule_parameters (ex. "0,002").

CREATE OR REPLACE FUNCTION public.parse_rule_numeric(t text, def numeric DEFAULT NULL)
RETURNS numeric
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
BEGIN
  t := TRIM(REPLACE(COALESCE(t, ''), ',', '.'));
  IF t = '' THEN RETURN def; END IF;
  RETURN t::numeric;
EXCEPTION WHEN OTHERS THEN
  RETURN def;
END;
$$;

COMMENT ON FUNCTION public.parse_rule_numeric(text, numeric) IS
  'Parse un nombre depuis rule_parameters : accepte virgule ou point décimal, retourne def si vide/invalide.';

CREATE OR REPLACE FUNCTION public.run_daily_country_update()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_at timestamptz;
  pop_base numeric;
  gdp_base numeric;
  gdp_per_mil numeric;
  gdp_per_ind numeric;
  gdp_per_sci numeric;
  gdp_per_stab numeric;
  pop_per_mil numeric;
  pop_per_ind numeric;
  pop_per_sci numeric;
  pop_per_stab numeric;
BEGIN
  v_run_at := now();

  INSERT INTO public.country_history (country_id, date, population, gdp, militarism, industry, science, stability)
  SELECT c.id, current_date, c.population, c.gdp, c.militarism, c.industry, c.science, c.stability
  FROM public.countries c
  ON CONFLICT (country_id, date)
  DO UPDATE SET population = EXCLUDED.population, gdp = EXCLUDED.gdp, militarism = EXCLUDED.militarism, industry = EXCLUDED.industry, science = EXCLUDED.science, stability = EXCLUDED.stability;

  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0.001), 0.001) INTO pop_base FROM public.rule_parameters WHERE key = 'population_growth_base_rate' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0.0005), 0.0005) INTO gdp_base FROM public.rule_parameters WHERE key = 'gdp_growth_base_rate' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO gdp_per_mil FROM public.rule_parameters WHERE key = 'gdp_growth_per_militarism' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO gdp_per_ind FROM public.rule_parameters WHERE key = 'gdp_growth_per_industry' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO gdp_per_sci FROM public.rule_parameters WHERE key = 'gdp_growth_per_science' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO gdp_per_stab FROM public.rule_parameters WHERE key = 'gdp_growth_per_stability' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO pop_per_mil FROM public.rule_parameters WHERE key = 'population_growth_per_militarism' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO pop_per_ind FROM public.rule_parameters WHERE key = 'population_growth_per_industry' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO pop_per_sci FROM public.rule_parameters WHERE key = 'population_growth_per_science' LIMIT 1;
  SELECT COALESCE(parse_rule_numeric(value #>> '{}', 0), 0) INTO pop_per_stab FROM public.rule_parameters WHERE key = 'population_growth_per_stability' LIMIT 1;

  WITH
  world_avgs AS (
    SELECT
      AVG(population)::numeric AS pop_avg,
      AVG(gdp)::numeric AS gdp_avg,
      AVG(militarism)::numeric AS mil_avg,
      AVG(industry)::numeric AS ind_avg,
      AVG(science)::numeric AS sci_avg,
      AVG(stability)::numeric AS stab_avg
    FROM public.countries
  ),
  pop_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('population_growth_base', 'population_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  gdp_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('gdp_growth_base', 'gdp_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  stat_effects AS (SELECT country_id, COALESCE(SUM(value) FILTER (WHERE effect_target = 'militarism'), 0) AS delta_mil, COALESCE(SUM(value) FILTER (WHERE effect_target = 'industry'), 0) AS delta_ind, COALESCE(SUM(value) FILTER (WHERE effect_target = 'science'), 0) AS delta_sci, COALESCE(SUM(value) FILTER (WHERE effect_target = 'stability'), 0) AS delta_stab FROM public.country_effects WHERE effect_kind = 'stat_delta' AND duration_remaining > 0 AND effect_target IN ('militarism', 'industry', 'science', 'stability') GROUP BY country_id),
  budget_raw AS (
    SELECT b.country_id,
      wa.mil_avg, wa.ind_avg, wa.sci_avg, wa.stab_avg,
      c.militarism AS mil_val, c.industry AS ind_val, c.science AS sci_val, c.stability AS stab_val,
      (CASE WHEN b.pct_sante >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) THEN (b.pct_sante/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'population' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) - b.pct_sante) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'population' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), -0.05), -0.05) END) AS raw_pop,
      (CASE WHEN b.pct_infrastructure >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) THEN (b.pct_infrastructure/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) - b.pct_infrastructure) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05), -0.05) END) AS raw_gdp_infra,
      (CASE WHEN b.pct_affaires_etrangeres >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05), -0.05) END) AS raw_gdp_ae,
      (CASE WHEN b.pct_defense >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) THEN (b.pct_defense/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'militarism' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) - b.pct_defense) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'militarism' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), -0.05), -0.05) END) AS raw_mil,
      (CASE WHEN b.pct_infrastructure >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) THEN (b.pct_infrastructure/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) - b.pct_infrastructure) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05), -0.05) END) AS raw_ind_infra,
      (CASE WHEN b.pct_industrie >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) THEN (b.pct_industrie/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) - b.pct_industrie) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), -0.05), -0.05) END) AS raw_ind_ind,
      (CASE WHEN b.pct_education >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) THEN (b.pct_education/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'science' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) - b.pct_education) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'science' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05), -0.05) END) AS raw_sci_edu,
      (CASE WHEN b.pct_recherche >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) THEN (b.pct_recherche/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'science' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) - b.pct_recherche) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'science' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), -0.05), -0.05) END) AS raw_sci_rech,
      (CASE WHEN b.pct_education >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) THEN (b.pct_education/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) - b.pct_education) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05), -0.05) END) AS raw_stab_edu,
      (CASE WHEN b.pct_interieur >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) THEN (b.pct_interieur/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) - b.pct_interieur) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), -0.05), -0.05) END) AS raw_stab_int,
      (CASE WHEN b.pct_affaires_etrangeres >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05), -0.05) END) AS raw_stab_ae
    FROM public.country_budget b
    JOIN public.countries c ON c.id = b.country_id
    CROSS JOIN world_avgs wa
  ),
  budget_bonuses AS (
    SELECT r.country_id,
      r.raw_pop AS pop_rate,
      r.raw_gdp_infra + r.raw_gdp_ae AS gdp_rate,
      (r.raw_mil * (CASE WHEN r.raw_mil >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 50), 50)/100.0*(r.mil_avg - r.mil_val)/NULLIF(r.mil_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 50), 50)/100.0*(r.mil_val - r.mil_avg)/NULLIF(r.mil_avg,0))) END)) AS mil_delta,
      (r.raw_ind_infra * (CASE WHEN r.raw_ind_infra >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 50), 50)/100.0*(r.ind_avg - r.ind_val)/NULLIF(r.ind_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 50), 50)/100.0*(r.ind_val - r.ind_avg)/NULLIF(r.ind_avg,0))) END))
      + (r.raw_ind_ind * (CASE WHEN r.raw_ind_ind >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 50), 50)/100.0*(r.ind_avg - r.ind_val)/NULLIF(r.ind_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 50), 50)/100.0*(r.ind_val - r.ind_avg)/NULLIF(r.ind_avg,0))) END)) AS ind_delta,
      (r.raw_sci_edu * (CASE WHEN r.raw_sci_edu >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 50), 50)/100.0*(r.sci_avg - r.sci_val)/NULLIF(r.sci_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 50), 50)/100.0*(r.sci_val - r.sci_avg)/NULLIF(r.sci_avg,0))) END))
      + (r.raw_sci_rech * (CASE WHEN r.raw_sci_rech >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 50), 50)/100.0*(r.sci_avg - r.sci_val)/NULLIF(r.sci_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 50), 50)/100.0*(r.sci_val - r.sci_avg)/NULLIF(r.sci_avg,0))) END)) AS sci_delta,
      (r.raw_stab_edu + r.raw_stab_int + r.raw_stab_ae) AS stab_delta
    FROM budget_raw r
  ),
  country_updates AS (SELECT c.id AS country_id, COALESCE(pe.rate, 0) AS pop_effect_rate, COALESCE(ge.rate, 0) AS gdp_effect_rate, COALESCE(se.delta_mil, 0) AS delta_mil, COALESCE(se.delta_ind, 0) AS delta_ind, COALESCE(se.delta_sci, 0) AS delta_sci, COALESCE(se.delta_stab, 0) AS delta_stab, COALESCE(bb.pop_rate, 0) AS budget_pop_rate, COALESCE(bb.gdp_rate, 0) AS budget_gdp_rate, COALESCE(bb.mil_delta, 0) AS budget_mil, COALESCE(bb.ind_delta, 0) AS budget_ind, COALESCE(bb.sci_delta, 0) AS budget_sci, COALESCE(bb.stab_delta, 0) AS budget_stab FROM public.countries c LEFT JOIN pop_effects pe ON pe.country_id = c.id LEFT JOIN gdp_effects ge ON ge.country_id = c.id LEFT JOIN stat_effects se ON se.country_id = c.id LEFT JOIN budget_bonuses bb ON bb.country_id = c.id)
  INSERT INTO public.country_update_logs (country_id, run_at, inputs, population_before, gdp_before, militarism_before, industry_before, science_before, stability_before)
  SELECT c.id, v_run_at, jsonb_build_object('pop_base', pop_base, 'gdp_base', gdp_base, 'pop_from_stats', (COALESCE(c.militarism,0)*pop_per_mil+COALESCE(c.industry,0)*pop_per_ind+COALESCE(c.science,0)*pop_per_sci+COALESCE(c.stability,0)*pop_per_stab), 'gdp_from_stats', (COALESCE(c.militarism,0)*gdp_per_mil+COALESCE(c.industry,0)*gdp_per_ind+COALESCE(c.science,0)*gdp_per_sci+COALESCE(c.stability,0)*gdp_per_stab), 'pop_effect_rate', u.pop_effect_rate, 'gdp_effect_rate', u.gdp_effect_rate, 'budget_pop_rate', u.budget_pop_rate, 'budget_gdp_rate', u.budget_gdp_rate, 'pop_total_rate', (pop_base+COALESCE(c.militarism,0)*pop_per_mil+COALESCE(c.industry,0)*pop_per_ind+COALESCE(c.science,0)*pop_per_sci+COALESCE(c.stability,0)*pop_per_stab+u.pop_effect_rate+u.budget_pop_rate), 'gdp_total_rate', (gdp_base+COALESCE(c.militarism,0)*gdp_per_mil+COALESCE(c.industry,0)*gdp_per_ind+COALESCE(c.science,0)*gdp_per_sci+COALESCE(c.stability,0)*gdp_per_stab+u.gdp_effect_rate+u.budget_gdp_rate), 'delta_mil', u.delta_mil, 'delta_ind', u.delta_ind, 'delta_sci', u.delta_sci, 'delta_stab', u.delta_stab, 'budget_mil', u.budget_mil, 'budget_ind', u.budget_ind, 'budget_sci', u.budget_sci, 'budget_stab', u.budget_stab), c.population, c.gdp, c.militarism, c.industry, c.science, c.stability FROM public.countries c JOIN country_updates u ON u.country_id = c.id;

  WITH
  world_avgs AS (
    SELECT
      AVG(population)::numeric AS pop_avg,
      AVG(gdp)::numeric AS gdp_avg,
      AVG(militarism)::numeric AS mil_avg,
      AVG(industry)::numeric AS ind_avg,
      AVG(science)::numeric AS sci_avg,
      AVG(stability)::numeric AS stab_avg
    FROM public.countries
  ),
  pop_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('population_growth_base', 'population_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  gdp_effects AS (SELECT country_id, SUM(CASE WHEN ABS(value) > 1 THEN value / 100.0 ELSE value END) AS rate FROM public.country_effects WHERE effect_kind IN ('gdp_growth_base', 'gdp_growth_per_stat') AND duration_remaining > 0 GROUP BY country_id),
  stat_effects AS (SELECT country_id, COALESCE(SUM(value) FILTER (WHERE effect_target = 'militarism'), 0) AS delta_mil, COALESCE(SUM(value) FILTER (WHERE effect_target = 'industry'), 0) AS delta_ind, COALESCE(SUM(value) FILTER (WHERE effect_target = 'science'), 0) AS delta_sci, COALESCE(SUM(value) FILTER (WHERE effect_target = 'stability'), 0) AS delta_stab FROM public.country_effects WHERE effect_kind = 'stat_delta' AND duration_remaining > 0 AND effect_target IN ('militarism', 'industry', 'science', 'stability') GROUP BY country_id),
  budget_raw AS (
    SELECT b.country_id,
      wa.mil_avg, wa.ind_avg, wa.sci_avg, wa.stab_avg,
      c.militarism AS mil_val, c.industry AS ind_val, c.science AS sci_val, c.stability AS stab_val,
      (CASE WHEN b.pct_sante >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) THEN (b.pct_sante/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'population' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0) - b.pct_sante) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'population' FROM public.rule_parameters WHERE key = 'budget_sante' LIMIT 1), -0.05), -0.05) END) AS raw_pop,
      (CASE WHEN b.pct_infrastructure >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) THEN (b.pct_infrastructure/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) - b.pct_infrastructure) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05), -0.05) END) AS raw_gdp_infra,
      (CASE WHEN b.pct_affaires_etrangeres >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'gdp' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05), -0.05) END) AS raw_gdp_ae,
      (CASE WHEN b.pct_defense >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) THEN (b.pct_defense/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'militarism' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0) - b.pct_defense) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'militarism' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), -0.05), -0.05) END) AS raw_mil,
      (CASE WHEN b.pct_infrastructure >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) THEN (b.pct_infrastructure/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0) - b.pct_infrastructure) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), -0.05), -0.05) END) AS raw_ind_infra,
      (CASE WHEN b.pct_industrie >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) THEN (b.pct_industrie/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0) - b.pct_industrie) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'industry' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), -0.05), -0.05) END) AS raw_ind_ind,
      (CASE WHEN b.pct_education >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) THEN (b.pct_education/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'science' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) - b.pct_education) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'science' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05), -0.05) END) AS raw_sci_edu,
      (CASE WHEN b.pct_recherche >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) THEN (b.pct_recherche/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'science' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0) - b.pct_recherche) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'science' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), -0.05), -0.05) END) AS raw_sci_rech,
      (CASE WHEN b.pct_education >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) THEN (b.pct_education/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0) - b.pct_education) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), -0.05), -0.05) END) AS raw_stab_edu,
      (CASE WHEN b.pct_interieur >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) THEN (b.pct_interieur/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0) - b.pct_interieur) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_interieur' LIMIT 1), -0.05), -0.05) END) AS raw_stab_int,
      (CASE WHEN b.pct_affaires_etrangeres >= COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) THEN (b.pct_affaires_etrangeres/100.0)*COALESCE(parse_rule_numeric((SELECT value->'bonuses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) ELSE ( (COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0) - b.pct_affaires_etrangeres) / NULLIF(COALESCE(parse_rule_numeric((SELECT value->>'min_pct' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), 0), 0), 0) ) * COALESCE(parse_rule_numeric((SELECT value->'maluses'->>'stability' FROM public.rule_parameters WHERE key = 'budget_affaires_etrangeres' LIMIT 1), -0.05), -0.05) END) AS raw_stab_ae
    FROM public.country_budget b
    JOIN public.countries c ON c.id = b.country_id
    CROSS JOIN world_avgs wa
  ),
  budget_bonuses AS (
    SELECT r.country_id,
      r.raw_pop AS pop_rate,
      r.raw_gdp_infra + r.raw_gdp_ae AS gdp_rate,
      (r.raw_mil * (CASE WHEN r.raw_mil >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 50), 50)/100.0*(r.mil_avg - r.mil_val)/NULLIF(r.mil_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_defense' LIMIT 1), 50), 50)/100.0*(r.mil_val - r.mil_avg)/NULLIF(r.mil_avg,0))) END)) AS mil_delta,
      (r.raw_ind_infra * (CASE WHEN r.raw_ind_infra >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 50), 50)/100.0*(r.ind_avg - r.ind_val)/NULLIF(r.ind_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_infrastructure' LIMIT 1), 50), 50)/100.0*(r.ind_val - r.ind_avg)/NULLIF(r.ind_avg,0))) END))
      + (r.raw_ind_ind * (CASE WHEN r.raw_ind_ind >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 50), 50)/100.0*(r.ind_avg - r.ind_val)/NULLIF(r.ind_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_industrie' LIMIT 1), 50), 50)/100.0*(r.ind_val - r.ind_avg)/NULLIF(r.ind_avg,0))) END)) AS ind_delta,
      (r.raw_sci_edu * (CASE WHEN r.raw_sci_edu >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 50), 50)/100.0*(r.sci_avg - r.sci_val)/NULLIF(r.sci_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_education' LIMIT 1), 50), 50)/100.0*(r.sci_val - r.sci_avg)/NULLIF(r.sci_avg,0))) END))
      + (r.raw_sci_rech * (CASE WHEN r.raw_sci_rech >= 0 THEN GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 50), 50)/100.0*(r.sci_avg - r.sci_val)/NULLIF(r.sci_avg,0))) ELSE GREATEST(0.1, LEAST(2, 1 + COALESCE(parse_rule_numeric((SELECT value->>'gravity_pct' FROM public.rule_parameters WHERE key = 'budget_recherche' LIMIT 1), 50), 50)/100.0*(r.sci_val - r.sci_avg)/NULLIF(r.sci_avg,0))) END)) AS sci_delta,
      (r.raw_stab_edu + r.raw_stab_int + r.raw_stab_ae) AS stab_delta
    FROM budget_raw r
  ),
  country_updates AS (SELECT c.id AS country_id, COALESCE(pe.rate, 0) AS pop_effect_rate, COALESCE(ge.rate, 0) AS gdp_effect_rate, COALESCE(se.delta_mil, 0) AS delta_mil, COALESCE(se.delta_ind, 0) AS delta_ind, COALESCE(se.delta_sci, 0) AS delta_sci, COALESCE(se.delta_stab, 0) AS delta_stab, COALESCE(bb.pop_rate, 0) AS budget_pop_rate, COALESCE(bb.gdp_rate, 0) AS budget_gdp_rate, COALESCE(bb.mil_delta, 0) AS budget_mil, COALESCE(bb.ind_delta, 0) AS budget_ind, COALESCE(bb.sci_delta, 0) AS budget_sci, COALESCE(bb.stab_delta, 0) AS budget_stab FROM public.countries c LEFT JOIN pop_effects pe ON pe.country_id = c.id LEFT JOIN gdp_effects ge ON ge.country_id = c.id LEFT JOIN stat_effects se ON se.country_id = c.id LEFT JOIN budget_bonuses bb ON bb.country_id = c.id)
  UPDATE public.countries c
  SET
    population = GREATEST(0, (c.population + c.population * (pop_base + COALESCE(c.militarism, 0) * pop_per_mil + COALESCE(c.industry, 0) * pop_per_ind + COALESCE(c.science, 0) * pop_per_sci + COALESCE(c.stability, 0) * pop_per_stab + u.pop_effect_rate + u.budget_pop_rate))::bigint),
    gdp = GREATEST(0, (c.gdp + c.gdp * (gdp_base + COALESCE(c.militarism, 0) * gdp_per_mil + COALESCE(c.industry, 0) * gdp_per_ind + COALESCE(c.science, 0) * gdp_per_sci + COALESCE(c.stability, 0) * gdp_per_stab + u.gdp_effect_rate + u.budget_gdp_rate))),
    militarism = LEAST(10, GREATEST(0, ROUND((COALESCE(c.militarism, 0) + u.delta_mil + u.budget_mil)::numeric, 2)))::numeric(4,2),
    industry   = LEAST(10, GREATEST(0, ROUND((COALESCE(c.industry, 0)   + u.delta_ind + u.budget_ind)::numeric, 2)))::numeric(4,2),
    science    = LEAST(10, GREATEST(0, ROUND((COALESCE(c.science, 0)    + u.delta_sci + u.budget_sci)::numeric, 2)))::numeric(4,2),
    stability  = LEAST(3, GREATEST(-3, ROUND((COALESCE(c.stability, 0) + u.delta_stab + u.budget_stab)::numeric, 2)))::numeric(4,2),
    updated_at = now()
  FROM country_updates u
  WHERE c.id = u.country_id;

  UPDATE public.country_update_logs l SET population_after = c.population, gdp_after = c.gdp, militarism_after = c.militarism, industry_after = c.industry, science_after = c.science, stability_after = c.stability FROM public.countries c WHERE l.country_id = c.id AND l.run_at = v_run_at;

  UPDATE public.country_effects SET duration_remaining = duration_remaining - 1 WHERE duration_remaining > 0;
  DELETE FROM public.country_effects WHERE duration_remaining <= 0;
END;
$$;
