-- Partie 1/2 : vue intermédiaire (jusqu'à budget_with_gravity) pour rester sous limite taille statement.

CREATE OR REPLACE VIEW public.cron_budget_bonuses_bwg AS
WITH wa AS (SELECT avg(population)::numeric AS pop_avg,avg(gdp)::numeric AS gdp_avg,avg(militarism)::numeric AS mil_avg,avg(industry)::numeric AS ind_avg,avg(science)::numeric AS sci_avg,avg(stability)::numeric AS stab_avg FROM public.countries),
bmp AS (SELECT c.id AS country_id,r.key AS ministry_key,CASE r.key WHEN 'budget_etat' THEN COALESCE(b.pct_etat,0) WHEN 'budget_education' THEN COALESCE(b.pct_education,0) WHEN 'budget_recherche' THEN COALESCE(b.pct_recherche,0) WHEN 'budget_infrastructure' THEN COALESCE(b.pct_infrastructure,0) WHEN 'budget_sante' THEN COALESCE(b.pct_sante,0) WHEN 'budget_industrie' THEN COALESCE(b.pct_industrie,0) WHEN 'budget_defense' THEN COALESCE(b.pct_defense,0) WHEN 'budget_interieur' THEN COALESCE(b.pct_interieur,0) WHEN 'budget_affaires_etrangeres' THEN COALESCE(b.pct_affaires_etrangeres,0) ELSE 0 END AS pct,COALESCE((r.value->>'min_pct')::numeric,5) AS min_pct,COALESCE((r.value->>'gravity_pct')::numeric,50) AS gravity_pct,r.value AS rule_value FROM public.countries c LEFT JOIN public.country_budget b ON b.country_id=c.id CROSS JOIN public.rule_parameters r WHERE r.key IN ('budget_etat','budget_education','budget_recherche','budget_infrastructure','budget_sante','budget_industrie','budget_defense','budget_interieur','budget_affaires_etrangeres')),
bea AS (SELECT mp.country_id,mp.ministry_key,mp.pct,mp.min_pct,mp.gravity_pct,e->>'effect_type' AS effect_type,COALESCE((e->>'bonus')::numeric,0) AS bonus,COALESCE((e->>'malus')::numeric,-0.05) AS malus,COALESCE((e->>'gravity_applies')::boolean,(e->>'effect_type') IN ('militarism','industry','science','stability')) AS gravity_applies FROM bmp mp,LATERAL jsonb_array_elements(mp.rule_value->'effects') AS e WHERE jsonb_typeof(mp.rule_value->'effects')='array' AND jsonb_array_length(mp.rule_value->'effects')>0 AND (e->>'effect_type') IN ('population','gdp','militarism','industry','science','stability')),
beb AS (SELECT mp.country_id,mp.ministry_key,mp.pct,mp.min_pct,mp.gravity_pct,ek.key AS effect_type,(ek.value)::numeric AS bonus,COALESCE((mp.rule_value->'maluses'->>ek.key)::numeric,-0.05) AS malus,ek.key IN ('militarism','industry','science','stability') AS gravity_applies FROM bmp mp,LATERAL jsonb_each_text(COALESCE(mp.rule_value->'bonuses','{}'::jsonb)) AS ek WHERE (mp.rule_value->'effects' IS NULL OR jsonb_array_length(COALESCE(mp.rule_value->'effects','[]'::jsonb))=0) AND ek.key IN ('population','gdp','militarism','industry','science','stability')),
ber AS (SELECT * FROM bea UNION ALL SELECT * FROM beb),
bc AS (SELECT country_id,ministry_key,effect_type,gravity_pct,gravity_applies,bonus,malus,CASE WHEN pct>=min_pct THEN (pct/100.0)*bonus ELSE ((min_pct-pct)/NULLIF(min_pct,0))*malus END AS contrib FROM ber),
bwg AS (SELECT bc.country_id,bc.effect_type,bc.contrib,bc.gravity_applies,bc.gravity_pct,c.population AS country_pop,c.gdp AS country_gdp,c.militarism AS country_mil,c.industry AS country_ind,c.science AS country_sci,c.stability AS country_stab,wa.pop_avg,wa.gdp_avg,wa.mil_avg,wa.ind_avg,wa.sci_avg,wa.stab_avg FROM bc JOIN public.countries c ON c.id=bc.country_id CROSS JOIN wa)
SELECT * FROM bwg;
